name: Daily Commit

on:
  schedule:
    # Runs daily at 02:30 UTC
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  daily_commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (step by 23f1002440@ds.study.iitm.ac.in)
        uses: actions/checkout@v3

      - name: Update timestamp file (step by 23f1002440@ds.study.iitm.ac.in)
        run: echo "Last updated at $(date -u)" > last_update.txt

      - name: Commit and push changes (step by 23f1002440@ds.study.iitm.ac.in)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_update.txt
          git commit -m "Automated daily commit - update timestamp"
          git push
