name: Daily Commit

on:
  schedule:
    # Runs daily at 02:30 UTC
    - cron: '50 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily_commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for pushing

      - name: Update timestamp file
        run: echo "Last updated at $(date -u)" > last_update.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_update.txt
          git commit -m "Automated daily commit - update timestamp"
          git push
